name: test-package-managers
on: [pull_request]
jobs:
  check_cocoapods:
    name: Check CocoaPods
    runs-on: macOS-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Install CocoaPod dependencies
        run: pod install
      - name: Run pod lib lint
        run: pod lib lint --allow-warnings
  check_carthage:
    name: Check Carthage
    runs-on: macOS-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Remove SPMTest
        run: rm -rf SampleApps/SPMTest && git add . && git commit -m 'Remove SPMTest app to avoid Carthage timeout'
      - name: Update Cartfile
        run: echo "git \"file://${PWD}\" \"$(git symbolic-ref --short HEAD)\"" > SampleApps/CarthageTest/Cartfile
      - name: Run carthage update
        run: cd SampleApps/CarthageTest && carthage update
      - name: Build CarthageTest
        run: xcodebuild -project 'SampleApps/CarthageTest/CarthageTest.xcodeproj' -scheme 'CarthageTest' clean build
